### ISSUE TITLE
hex encodings and strings

### ISSUE THREAD

**Issue by dgryski** [conformal/yubikey#11]
The standard library provides encoding/hex which can do the encoding and decoding from hex bytes in strings to []bytes.

Similarly, I think NewUid and NewKey, which are taking strings containing binary data, should be updated to take a []byte (with length checks, etc) instead or be defined to take a hexstring which is then decoded.

**Comment by dgryski** [comment]
Oops, changed the title of the bug report and lost some context. I think ykhex.go can be deleted, but depending on how the rest of the API bits act w.r.t. strings and binary data might change how we fix this.

If we adjust the APIs that take strings to taking slices of bytes, then it's easy to move to encoding/hex and remove ykhex completely. However, if you want to keep the APIs taking stings of binary data, then we should keep the string->string functions (although perhaps replace the internals).

**Comment by dajohi** [comment]
I agree the APIs should be taking bytes.

**Comment by dgryski** [comment]
I have a WIP patch that does this. I'll clean it up and push it tonight along with moving to encoding/hex.

**Comment by dgryski** [comment]
This is done
