### ISSUE TITLE
No way to check crc of a decrypted token

### ISSUE THREAD

**Issue by dgryski** [conformal/yubikey#2]
Parse() should probably check the crc after decrypting the OTP., and return a 'corrupt otp' error if CrcOkP returns false.

I wasn't sure if you wanted to add this, which is why I filed a bug instead of a pull request.

I understand that you're mirroring the C API as much as possible, which suggests to use the non-existent "yubikey_check_*" functions.

**Comment by dajohi** [comment]
Yes, I agree Parse() should do the CrcOkP check and return an error if it fails.  Do you want to make a diff?

**Comment by dgryski** [comment]
Yes, I'll submit a pull request tonight (Amsterdam time).

**Comment by dgryski** [comment]
Pull  request #2
